# Generated by Django 5.0.6 on 2024-05-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
