# Generated by Django 5.0.6 on 2024-05-17 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 30, 22, 58, 22, 257802)),
        ),
    ]
