# Generated by Django 5.0.6 on 2024-05-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_alter_borrowedbook_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
    ]
