# Generated by Django 5.0.6 on 2024-05-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_customuser_contact_number_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='contact_number',
            new_name='contact',
        ),
    ]
