# Generated by Django 5.0.6 on 2024-05-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(),
        ),
    ]
